# docker-compose.yml

services:
  # This is the service name for our MongoDB database
  mongo-db:
    #DEVNOTE: using specific version can help avoid compatibility problem later but....
    image: mongo:latest
    restart: always
    # Environment variables for the root user of the database
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    # This maps the default MongoDB port (27017) to the same port on our host machine.
    # no port conflicts while using specific high ports. already tired of this lol!
    ports:
      - "27017:27017"
    # This creates a volume to persist the database data.
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
